#esto conecta bien con supabase - anda contra supabase cuando tengo la API en railway
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8081}


# CONFIGURACION QUE ANDA CON SUPABASE - esta anda para probar probar contra supabase, pero con la API en local
#spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
#spring.datasource.username=postgres.thclutvoascdziaophcz
#spring.datasource.password=Jonas#12345TDF
#spring.jpa.hibernate.ddl-auto=update
#server.port=8081


# CONFIGURACION PARA LOCAL (usar esta cuando levanto springboot desde aca local)
#spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
#spring.datasource.username=task_user
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#server.port=8081

